[package]
name = "simpllm-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0" # for sampling logits
rayon = "1.11.0" # multithreading

[dev-dependencies]
# for unit tests:
approx = "0.5" # asserts for floats
tiktoken-rs = "0.11" # reference implementation of BPE tokenizer, to compare against
