#!/usr/bin/env bash
set -euo pipefail

for file_path in "$@"; do
  dir_path="$(dirname "$file_path")"
  file_name="$(basename "$file_path")"

  if [[ ! -f "$file_path" ]]; then
    echo >&2 "Missing file: $file_path"
    exit 1
  fi
  if [[ "$file_name" != *.drawio ]]; then
    echo >&2 "Skipping non-drawio file: $file_path"
    exit 1
  fi

  file_name_no_ext="${file_name%.*}"
  file_name_sha1="${file_name_no_ext}.sha1"
  if (cd "$dir_path" && &>/dev/null sha1sum -c "$file_name_sha1"); then
    echo >&2 "$file_path unchanged; skipping"
    continue
  fi

  full_dir="$(readlink -f "$dir_path")"
  for drawio_theme in light dark; do
    docker run --rm -i -w /data -v "$full_dir":/data rlespinasse/drawio-desktop-headless -x -f svg --svg-theme "$drawio_theme" -o "$file_name_no_ext-${drawio_theme}.svg" "$file_name" 2>>log.txt
  done
  (cd "$dir_path" && sha1sum "$file_name" >"$file_name_sha1")
done
