[package]
name = "download"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "download"
path = "src/main.rs"

[dependencies]
gpt2weights = { path = "../gpt2weights" }
clap = { workspace = true }
reqwest = { version = "0.13", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
indicatif = "0.18"
anyhow = "1.0"
futures-util = "0.3"
strum = "0.27"
strum_macros = "0.27"
safetensors = "0.7"
serde_json = { workspace = true }
memmap2 = "0.9.9"
