[package]
name = "simpllm"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "simpllm"
path = "src/main.rs"

[dependencies]
serde_json = { workspace = true }
rand = "0.10.0"
rayon = "1.11.0"
clap = { workspace = true }
gpt2weights = { path = "../gpt2weights" }

[dev-dependencies]
approx = "0.5"
tiktoken-rs = "0.9.1"
