#!/usr/bin/env bash
set -euo pipefail

plugin_dir=_plugin/drawio
mkdir -p "$plugin_dir"

# exec 2>>"$plugin_dir/log.txt"
# set -x

function svg_data() {
  printf 'data:image/svg+xml;base64,'
  cat - | base64
}

function error_svg() {
  local message="$(echo "$*" | sed 's/</\&lt;/g; s/>/\&gt;/g;')"
  printf '
    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 150 16" role="img" aria-label="Error">
      <text x="100%%" y="100%%" dominant-baseline="middle" text-anchor="middle"
          font-weight="700" font-size="10"
          fill="#B00020" stroke="rgba(255,255,255,0.9)" stroke-width="0.6" stroke-linejoin="round">%s</text>
    </svg>' "$message"
}

function render_drawio() {
  local theme="$1"
  local file_path="$2"

  local symlink_name="$(echo "$file_path" | sha1sum | cut -d' ' -f1)-$theme"

  if [[ ! -f "$drawio_file" ]]; then
    error_svg "Missing file: $drawio_file" | svg_data >"$plugin_dir/${symlink_name}.data"
  elif [[ "$drawio_file" != *.drawio ]]; then
    error_svg "Invalid file: $drawio_file" | svg_data >"$plugin_dir/${symlink_name}.data"
  else
    rm -f "$plugin_dir/${symlink_name}.drawio"
    cp "$file_path" "$plugin_dir/${symlink_name}.drawio"

    # regenerate the file if the the svg is missing, or if the drawio's sha1 changed
    if [[ ! -e "$plugin_dir/${symlink_name}.svg" ]] ||
      ! (cd "$plugin_dir" && sha1sum -c "${symlink_name}.sha" >/dev/null 2>&1); then
      >&2 docker run --rm -i -w /data -v "$PWD/$plugin_dir":/data rlespinasse/drawio-desktop-headless -x -f svg \
        --svg-theme "$theme" -o "${symlink_name}.svg" "$symlink_name.drawio"
      cat "$plugin_dir/${symlink_name}.svg" | svg_data >"$plugin_dir/${symlink_name}.data"
      (cd "$plugin_dir" && sha1sum "$symlink_name.drawio" >"$symlink_name.sha")
    fi
  fi
  echo "$plugin_dir/${symlink_name}.data"
}

if [[ "$#" -eq 0 ]]; then
  echo '{
    "name": "Drawio Render",
    "roles": [
      {
        "name": "drawio",
        "doc": "render a drawio document",
        "body": {
          "type": "string",
          "required": true,
          "doc": "the path to the drawio document, without the \".drawio\" file extension"
        }
      }
    ]
  }'
  exit
fi

if [[ "$1" != '--role' || "$2" != 'drawio' ]]; then
  echo "Unrecognized options: $@" >err.txt
  exit 1
fi

target="$(cat - | jq -r '.node.value')"

drawio_file="${target}.drawio"

dark_svg_data="$(render_drawio dark "$drawio_file")"
light_svg_data="$(render_drawio light "$drawio_file")"

jq -n \
  \
  --rawfile dark "$dark_svg_data" \
  --rawfile light "$light_svg_data" \
  '[{
  type: "span",
  class: "theme-aware-wrapper",
  children: [
    {
      type: "span",
      class: "hidden dark:block",
      children: [{
        "type": "image",
        "url": $dark
      }]
    },
    {
      type: "span",
      class: "dark:hidden",
      children: [{
        "type": "image",
        "url": $light
      }]
    }
  ]
}]'
