#!/usr/bin/env bash
set -euo pipefail

plugin_dir=_plugin/drawio
mkdir -p "$plugin_dir"

# exec 2>>"$plugin_dir/log.txt"
# set -x

function svg_data() {
  printf 'data:image/svg+xml;base64,'
  cat - | base64 -w0
}

function error_svg() {
  echo >&2 "$*"
  local message="$(echo "$*" | sed 's/</\&lt;/g; s/>/\&gt;/g;')"
  printf '
    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 150 16" role="img" aria-label="Error">
      <text x="100%%" y="100%%" dominant-baseline="middle" text-anchor="middle"
          font-weight="700" font-size="10"
          fill="#B00020" stroke="rgba(255,255,255,0.9)" stroke-width="0.6" stroke-linejoin="round">%s</text>
    </svg>' "$message"
}

function render_drawio() {
  local theme="$1"
  local file_path="$2"

  local symlink_name="$(echo "$file_path" | sha1sum | cut -d' ' -f1)-$theme"

  if [[ ! -f "$drawio_file" ]]; then
    error_svg "Missing file: $drawio_file" | svg_data >"$plugin_dir/${symlink_name}.data"
    exit 1
  elif [[ "$drawio_file" != *.drawio ]]; then
    error_svg "Invalid file: $drawio_file" | svg_data >"$plugin_dir/${symlink_name}.data"
    exit 1
  else
    rm -f "$plugin_dir/${symlink_name}.drawio"
    cp "$file_path" "$plugin_dir/${symlink_name}.drawio"

    # regenerate the file if the the svg is missing, or if the drawio's sha1 changed
    if [[ ! -e "$plugin_dir/${symlink_name}.svg" ]] ||
      ! (cd "$plugin_dir" && sha1sum -c "${symlink_name}.sha" >/dev/null 2>&1); then
      >&2 docker run --rm -i -w /data -v "$PWD/$plugin_dir":/data rlespinasse/drawio-desktop-headless -x -f svg \
        --svg-theme "$theme" -o "${symlink_name}.svg" "$symlink_name.drawio"
      cat "$plugin_dir/${symlink_name}.svg" | svg_data >"$plugin_dir/${symlink_name}.data"
      (cd "$plugin_dir" && sha1sum "$symlink_name.drawio" >"$symlink_name.sha")
    fi
  fi
  echo "$plugin_dir/${symlink_name}.data"
}

if [[ "$#" -eq 0 ]]; then
  echo '{
    "name": "Drawio Render",
    "roles": [
      {
        "name": "drawio",
        "doc": "render a drawio document",
        "body": {
          "type": "string",
          "required": true,
          "doc": "the path to the drawio document, without the \".drawio\" file extension"
        }
      }
    ],
    "directives": [
      {
        "name": "drawio",
        "doc": "render a drawio document",
        "arg": {
          "type": "string",
          "doc": "the path to the drawio document, without the \".drawio\" file extension"
        },
        "options": {
          "alt": {
            "type": "string",
            "doc": "Alt text for the image"
          }
        }
      }
    ]
  }'
  exit
fi

if [[ "$2" != 'drawio' ]]; then
  echo "Unrecognized options: $@" >&2
  exit 1
fi

case "$1" in
--role)
  # read the target as "<alt>|<path>".
  # If <path> is empty, then flip it so that <alt> is empty.
  IFS='|' read -r target_alt target_path <<<"$(cat - | jq -r '.node.value')"
  if [[ -z "$target_path" ]]; then
    target_path="$target_alt"
    target_alt=""
  fi
  ;;
--directive)
  all_input="$(cat -)"
  target_path="$(echo "$all_input" | jq -r .arg)"
  target_alt="$(echo "$all_input" | jq -r '.options.alt // ""')"
  ;;
*)
  echo "Unrecognized options: $@" >&2
  exit 1
  ;;
esac

drawio_file="${target_path}.drawio"

dark_svg_data="$(render_drawio dark "$drawio_file")"
light_svg_data="$(render_drawio light "$drawio_file")"

# Workaround for large files
tmp_file="$plugin_dir/$(uuidgen).json"
jq -n \
  \
  --rawfile dark "$dark_svg_data" \
  --rawfile light "$light_svg_data" \
  --arg alt "$target_alt" \
  '[{
  type: "span",
  class: "theme-aware-wrapper",
  children: [
    {
      type: "span",
      class: "hidden dark:block",
      children: [{
        "type": "image",
        "url": $dark,
        "alt": (if $alt == "" then null else $alt end)
      }]
    },
    {
      type: "span",
      class: "dark:hidden",
      children: [{
        "type": "image",
        "url": $light,
        "alt": (if $alt == "" then null else $alt end)
      }]
    }
  ]
}]' >"$tmp_file"
if jq . "$tmp_file" >/dev/null; then
  cat "$tmp_file"
  rm "$tmp_file"
else
  mv "$tmp_file" "$plugin_dir/BROKEN-$(echo "$drawio_file" | sed 's/\//-/g').json"
  echo '[]'
  exit 1
fi
